/*
 * JTraceGUI.java
 *
 * Created on July 29, 2004, 10:12 PM
 */

package net.geckotales.jtrace.gui;

/**
 *
 * @author  marma
 */
public class JTraceGUI extends javax.swing.JFrame {
    
    /** Creates new form JTraceGUI */
    public JTraceGUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        tabbedPane = new javax.swing.JTabbedPane();
        textPane = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        renderPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        variancePane = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem1 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        viewMenu = new javax.swing.JMenu();
        renderMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        tabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabbedPane.setFocusable(false);
        tabbedPane.setFont(new java.awt.Font("Dialog", 0, 12));
        textPane.setMinimumSize(new java.awt.Dimension(320, 240));
        textPane.setPreferredSize(new java.awt.Dimension(320, 240));
        textPane.setViewportView(jTextArea1);

        tabbedPane.addTab("text", textPane);

        renderPane.setViewportView(jPanel1);

        tabbedPane.addTab("image", renderPane);

        variancePane.setViewportView(jPanel2);

        tabbedPane.addTab("variance", variancePane);

        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Dialog", 0, 12));
        openMenuItem.setFont(new java.awt.Font("Dialog", 0, 12));
        openMenuItem.setText("Open ...");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });

        fileMenu.add(openMenuItem);

        saveMenuItem.setFont(new java.awt.Font("Dialog", 0, 12));
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem1.setFont(new java.awt.Font("Dialog", 0, 12));
        saveAsMenuItem1.setText("Save As ...");
        fileMenu.add(saveAsMenuItem1);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");
        editMenu.setFont(new java.awt.Font("Dialog", 0, 12));
        editMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuActionPerformed(evt);
            }
        });

        menuBar.add(editMenu);

        viewMenu.setText("View");
        viewMenu.setFont(new java.awt.Font("Dialog", 0, 12));
        menuBar.add(viewMenu);

        renderMenu.setText("Render");
        renderMenu.setFont(new java.awt.Font("Dialog", 0, 12));
        renderMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renderMenuActionPerformed(evt);
            }
        });

        menuBar.add(renderMenu);

        setJMenuBar(menuBar);

        pack();
    }//GEN-END:initComponents

    private void renderMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renderMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_renderMenuActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void editMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTraceGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenu renderMenu;
    private javax.swing.JScrollPane renderPane;
    private javax.swing.JMenuItem saveAsMenuItem1;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JScrollPane textPane;
    private javax.swing.JScrollPane variancePane;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
    
}
