/*
 * ImageViewer.java
 *
 * Created on July 25, 2004, 5:50 PM
 */

package net.geckotales.jtrace;

/**
 *
 * @author  marma
 */
public class ImageViewer extends javax.swing.JFrame {
    
    /** Creates new form ImageViewer */
    public ImageViewer() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 12));
        jPanel1.setMinimumSize(new java.awt.Dimension(320, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 240));
        jScrollPane1.setViewportView(jPanel1);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        jPanel2.setMinimumSize(new java.awt.Dimension(320, 240));
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 240));
        jScrollPane2.setViewportView(jPanel2);

        jTabbedPane1.addTab("tab2", jScrollPane2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageViewer().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
}
